//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IslamicUloom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.Abwaabs = new HashSet<Abwaab>();
            this.Pages = new HashSet<Page>();
        }
    
        public int BookId { get; set; }
        public string BookName { get; set; }
        public int PublisherId { get; set; }
        public int AuthorId { get; set; }

        
        public System.DateTime PublishingYear { get; set; }
        public int EditionNumber { get; set; }
        public string UserName { get; set; }
        public string BookCompleted { get; set; }
        public Nullable<int> NumberOfPages { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Abwaab> Abwaabs { get; set; }
        public virtual Author Author { get; set; }
        public virtual Publisher Publisher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Page> Pages { get; set; }
    }
}
