//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IslamicUloom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookMark
    {
        public int BookMarkID { get; set; }
        public string BookMarkName { get; set; }
    }
}
